/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multilista;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author leeyn
 */
public class Launcher extends javax.swing.JFrame {

    /**
     * Creates new form Launcher
     */
    public Launcher() {
        initComponents();
    }

    MultiLista multi = new MultiLista("UD");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spn = new javax.swing.JScrollPane();
        pns = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAgrMateria = new javax.swing.JButton();
        btnAgrEstudiante = new javax.swing.JButton();
        btnEliMateria = new javax.swing.JButton();
        btnEliEstudiante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pns.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.light"));
        pns.setPreferredSize(new java.awt.Dimension(4000, 4000));

        javax.swing.GroupLayout pnsLayout = new javax.swing.GroupLayout(pns);
        pns.setLayout(pnsLayout);
        pnsLayout.setHorizontalGroup(
            pnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, Short.MAX_VALUE, Short.MAX_VALUE)
        );
        pnsLayout.setVerticalGroup(
            pnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, Short.MAX_VALUE, Short.MAX_VALUE)
        );

        spn.setViewportView(pns);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Universidad");

        btnAgrMateria.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnAgrMateria.setText("Agregar Materia");
        btnAgrMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrMateriaActionPerformed(evt);
            }
        });

        btnAgrEstudiante.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnAgrEstudiante.setText("Agrega Estudiante");
        btnAgrEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrEstudianteActionPerformed(evt);
            }
        });

        btnEliMateria.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnEliMateria.setText("Eliminar Materia");
        btnEliMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliMateriaActionPerformed(evt);
            }
        });

        btnEliEstudiante.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnEliEstudiante.setText("Eliminar Esrudiante");
        btnEliEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(spn, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnAgrMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnAgrEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnEliMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(spn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgrMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgrEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgrEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrEstudianteActionPerformed
        String sAgrEst = JOptionPane.showInputDialog(this, " Ingrese materia y alumno \n de la siguiente manera \n (Materia,Alumno)");
        String[] MatAlum = sAgrEst.split(",");
        multi.ingresarEstudiante(MatAlum[0], MatAlum[1]);

        mostrar(multi.escribir_lista());
    }//GEN-LAST:event_btnAgrEstudianteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnAgrMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrMateriaActionPerformed
        String materia = JOptionPane.showInputDialog(this, "Ingrese la materia");
        multi.ingresarMateria(materia);

        mostrar(multi.escribir_lista());
    }//GEN-LAST:event_btnAgrMateriaActionPerformed

    private void btnEliMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliMateriaActionPerformed
        String materia = JOptionPane.showInputDialog(this, "Ingrese la materia");
        multi.eliminarMateria(materia);
        mostrar(multi.escribir_lista());
    }//GEN-LAST:event_btnEliMateriaActionPerformed

    private void btnEliEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliEstudianteActionPerformed
        String sAgrEst = JOptionPane.showInputDialog(this, " Ingrese materia y alumno \n de la siguiente manera \n (Materia,Alumno)");
        String[] MatAlum = sAgrEst.split(",");
        multi.eliminarEstudiante(MatAlum[0], MatAlum[1]);
        mostrar(multi.escribir_lista());
    }//GEN-LAST:event_btnEliEstudianteActionPerformed

    public void mostrar(String[] arreglo) {

        pns.removeAll();

        int j = 1, k = 0;
        boolean flag = true;
        String[] gg = arreglo;

        for (int i = 0; i < gg.length; i++) {
            if (gg[i].equals("-")) {
                flag = false;
                System.out.println("Entra");

            } else if (gg[i].equals("+")) {
                flag = true;
                System.out.println("Entramo");
            }
            if (flag) {

                ImageIcon image2 = new ImageIcon("der.png");
                JLabel fle = new JLabel(image2);
                if (i != 0) {
                    fle.setBounds(110 * k, 50 * j, 100, 30);
                }

                k++;

                j = 1;
                if (!gg[i].equals("-") && !gg[i].equals("+")) {
                    JLabel x = new JLabel();
                    x.setText(" " + gg[i]);
                    x.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 81, 30)));
                    x.setBounds(110 * k, 50 * j, 100, 30);
                    pns.add(x);
                    if (i != 0) {
                        pns.add(fle);
                    }
                }

            } else {

                ImageIcon image1 = new ImageIcon("abjo2.png");
                JLabel flec = new JLabel(image1);

                    flec.setBounds(110 * k, 50 * j, 100, 30);

                if (!gg[i].equals("-")) {
                    j++;
                    JLabel x = new JLabel();
                    x.setText(" " + gg[i]);
                    x.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219)));
                    x.setBounds(110 * k, 50 * j, 100, 30);
                    pns.add(x);
                    pns.add(flec);
                }
                j++;
            }
        }
        pns.updateUI();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Launcher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgrEstudiante;
    private javax.swing.JButton btnAgrMateria;
    private javax.swing.JButton btnEliEstudiante;
    private javax.swing.JButton btnEliMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pns;
    private javax.swing.JScrollPane spn;
    // End of variables declaration//GEN-END:variables
}
