package matricesdispersas;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author leeyn
 */
public class Launcher extends javax.swing.JFrame {

    /**
     * Creates new form Launcher
     */
    Colunna cols = new Colunna();
    Matriz A = new Matriz("A");
    Matriz B = new Matriz("B");

    public Launcher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCa = new javax.swing.JTextField();
        txtFa = new javax.swing.JTextField();
        txtVa = new javax.swing.JTextField();
        btnInsA = new javax.swing.JButton();
        txtFb = new javax.swing.JTextField();
        txtVb = new javax.swing.JTextField();
        btnInsB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCb = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnA = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnB = new javax.swing.JPanel();
        btnSumar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Matrices Dispersas");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel2.setText("Colimna");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel3.setText("Fila");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel4.setText("Valor");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setText("Matriz A");

        txtCa.setToolTipText("");
        txtCa.setMaximumSize(new java.awt.Dimension(30, 30));
        txtCa.setMinimumSize(new java.awt.Dimension(30, 30));
        txtCa.setName(""); // NOI18N
        txtCa.setPreferredSize(new java.awt.Dimension(30, 30));

        txtFa.setToolTipText("");
        txtFa.setMaximumSize(new java.awt.Dimension(30, 30));
        txtFa.setMinimumSize(new java.awt.Dimension(30, 30));
        txtFa.setName(""); // NOI18N
        txtFa.setPreferredSize(new java.awt.Dimension(30, 30));

        txtVa.setToolTipText("");
        txtVa.setMaximumSize(new java.awt.Dimension(30, 30));
        txtVa.setMinimumSize(new java.awt.Dimension(30, 30));
        txtVa.setName(""); // NOI18N
        txtVa.setPreferredSize(new java.awt.Dimension(30, 30));

        btnInsA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnInsA.setText("Insertar");
        btnInsA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsAActionPerformed(evt);
            }
        });

        txtFb.setToolTipText("");
        txtFb.setMaximumSize(new java.awt.Dimension(30, 30));
        txtFb.setMinimumSize(new java.awt.Dimension(30, 30));
        txtFb.setName(""); // NOI18N
        txtFb.setPreferredSize(new java.awt.Dimension(30, 30));

        txtVb.setToolTipText("");
        txtVb.setMaximumSize(new java.awt.Dimension(30, 30));
        txtVb.setMinimumSize(new java.awt.Dimension(30, 30));
        txtVb.setName(""); // NOI18N
        txtVb.setPreferredSize(new java.awt.Dimension(30, 30));

        btnInsB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnInsB.setText("Insertar");
        btnInsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsBActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel6.setText("Colimna");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel7.setText("Fila");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel8.setText("Valor");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel9.setText("Matriz B");

        txtCb.setToolTipText("");
        txtCb.setMaximumSize(new java.awt.Dimension(30, 30));
        txtCb.setMinimumSize(new java.awt.Dimension(30, 30));
        txtCb.setName(""); // NOI18N
        txtCb.setPreferredSize(new java.awt.Dimension(30, 30));

        pnA.setPreferredSize(new java.awt.Dimension(1500, 1500));

        javax.swing.GroupLayout pnALayout = new javax.swing.GroupLayout(pnA);
        pnA.setLayout(pnALayout);
        pnALayout.setHorizontalGroup(
            pnALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        pnALayout.setVerticalGroup(
            pnALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnA);

        pnB.setPreferredSize(new java.awt.Dimension(1500, 1500));

        javax.swing.GroupLayout pnBLayout = new javax.swing.GroupLayout(pnB);
        pnB.setLayout(pnBLayout);
        pnBLayout.setHorizontalGroup(
            pnBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        pnBLayout.setVerticalGroup(
            pnBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(pnB);

        btnSumar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSumar.setText("SUMAR");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtVa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(28, 28, 28)
                                .addComponent(btnInsA))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtVb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addComponent(btnInsB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel9))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(455, 455, 455))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtFa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnInsA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtVa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtFb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnInsB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtVb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsAActionPerformed
        int Ca = Integer.parseInt(txtCa.getText());
        int Fa = Integer.parseInt(txtFa.getText());
        int Va = Integer.parseInt(txtVa.getText());

//        if (Va != 0) {
            A.ingColumna(Ca);
            A.ingFila(Ca, Fa, Va);
            cols.ins_final(Ca, Fa);
//        }
        mostrar(A.escribir_lista(),pnA);
    }//GEN-LAST:event_btnInsAActionPerformed

    private void btnInsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsBActionPerformed
     int Cb = Integer.parseInt(txtCb.getText());
        int Fb = Integer.parseInt(txtFb.getText());
        int Vb = Integer.parseInt(txtVb.getText());

//        if (Vb != 0) {
            B.ingColumna(Cb);
            B.ingFila(Cb, Fb, Vb);
            cols.ins_final(Cb, Fb);
//        }
        mostrar(B.escribir_lista(),pnB);
    }//GEN-LAST:event_btnInsBActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        
        Matriz C = new Matriz("C");
        int a, b, c;
        System.out.println(cols.size + " size");
        for (int i = 0; i < cols.size - 1; i++) {
//                System.out.println("(" + cols.cab.fila + " , " + cols.cab.valor + ")");
            if (cols.cab != null) {
                System.out.println("Enttrando mi compa");
                a = A.traer(cols.cab.fila, cols.cab.valor);
                b = B.traer(cols.cab.fila, cols.cab.valor);
                c = a+b;
                if(c != 0){                    
                    C.ingColumna(cols.cab.fila);
                    C.ingFila(cols.cab.fila, cols.cab.valor, c);
                }

                System.out.println("(" + cols.cab.fila + " , " + cols.cab.valor + ")");
                System.out.println(a + " a");
                System.out.println(b + " b");
                System.out.println(c + " c");
                System.out.println("");
                cols.sigui();
            }
        }
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        C.escribir_lista();
        
        Resul ser = new Resul(C.escribir_lista());
        ser.setLocationRelativeTo(null);
        ser.setVisible(true);
    }//GEN-LAST:event_btnSumarActionPerformed

    
    public void mostrar(String[] arreglo,JPanel pnP) {

        pnP.removeAll();

        int j = 1, k = 0;
        boolean flag = true;
        String[] gg = arreglo;

        for (int i = 0; i < gg.length; i++) {
            if (gg[i].equals("-")) {
                flag = false;
//                System.out.println("Entra");

            } else if (gg[i].equals("+")) {
                flag = true;
//                System.out.println("Entramo");
            }
            if (flag) {

                ImageIcon image2 = new ImageIcon("der.png");
                JLabel fle = new JLabel(image2);
                if (i != 0) {
                    fle.setBounds(70 * k, 40 * j, 60, 30);
                }

                k++;

                j = 1;
                if (!gg[i].equals("-") && !gg[i].equals("+")) {
                    JLabel x = new JLabel();
                    x.setText(" " + gg[i]);
                    x.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    x.setBounds(70 * k, 40 * j, 60, 30);
                    pnP.add(x);
                    if (i != 0) {
                        pnP.add(fle);
                    }
                }

            } else {

                ImageIcon image1 = new ImageIcon("abjo2.png");
                JLabel flec = new JLabel(image1);

                    flec.setBounds((70 * k)+10, 40 * j, 30, 30);

                if (!gg[i].equals("-")) {
                    j++;
                    JLabel x = new JLabel();
                    JLabel v = new JLabel();
                    String[] fv = gg[i].split(":");
                    x.setText(" " + fv[0]);
                    x.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    x.setBounds(70 * k, 40 * j, 30, 30);
                    
                    v.setText(" " + fv[1]);
                    v.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    v.setBounds((70 * k)+30, 40 * j, 30, 30);
                    pnP.add(x);
                    pnP.add(v);
                    pnP.add(flec);
                }
                j++;
            }
        }
        pnP.updateUI();
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Launcher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsA;
    private javax.swing.JButton btnInsB;
    private javax.swing.JButton btnSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnA;
    private javax.swing.JPanel pnB;
    private javax.swing.JTextField txtCa;
    private javax.swing.JTextField txtCb;
    private javax.swing.JTextField txtFa;
    private javax.swing.JTextField txtFb;
    private javax.swing.JTextField txtVa;
    private javax.swing.JTextField txtVb;
    // End of variables declaration//GEN-END:variables
}
