/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matricesdispersas;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author leeyn
 */
public class Resul extends javax.swing.JFrame {

    /**
     * Creates new form Resul
     */
//    Matriz A,B;
    String[] arreglo;

    public Resul(String[] arreglo) {
        this.arreglo = arreglo;
        initComponents();
    }
    
    
    public Resul() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnP = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnP.setOpaque(false);
        pnP.setPreferredSize(new java.awt.Dimension(2500, 2500));

        javax.swing.GroupLayout pnPLayout = new javax.swing.GroupLayout(pnP);
        pnP.setLayout(pnPLayout);
        pnPLayout.setHorizontalGroup(
            pnPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2500, Short.MAX_VALUE)
        );
        pnPLayout.setVerticalGroup(
            pnPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2500, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int j = 1, k = 0;
        boolean flag = true;
        String[] gg = arreglo;

        for (int i = 0; i < gg.length; i++) {
            if (gg[i].equals("-")) {
                flag = false;
                System.out.println("Entra");

            } else if (gg[i].equals("+")) {
                flag = true;
                System.out.println("Entramo");
            }
            if (flag) {

                ImageIcon image2 = new ImageIcon("der.png");
                JLabel fle = new JLabel(image2);
                if (i != 0) {
                    fle.setBounds(70 * k, 40 * j, 60, 30);
                }

                k++;

                j = 1;
                if (!gg[i].equals("-") && !gg[i].equals("+")) {
                    JLabel x = new JLabel();
                    x.setText(" " + gg[i]);
                    x.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    x.setBounds(70 * k, 40 * j, 60, 30);
                    pnP.add(x);
                    if (i != 0) {
                        pnP.add(fle);
                    }
                }

            } else {

                ImageIcon image1 = new ImageIcon("abjo2.png");
                JLabel flec = new JLabel(image1);

                    flec.setBounds((70 * k)+10, 40 * j, 30, 30);

                if (!gg[i].equals("-")) {
                    j++;
                    JLabel x = new JLabel();
                    JLabel v = new JLabel();
                    String[] fv = gg[i].split(":");
                    x.setText(" " + fv[0]);
                    x.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    x.setBounds(70 * k, 40 * j, 30, 30);
                    
                    v.setText(" " + fv[1]);
                    v.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    v.setBounds((70 * k)+30, 40 * j, 30, 30);
                    pnP.add(x);
                    pnP.add(v);
                    pnP.add(flec);
                }
                j++;
            }
        }
        pnP.updateUI();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnP;
    // End of variables declaration//GEN-END:variables
}
